### ISSUE TITLE
Episode 6, K8S 1.23.3

### ISSUE THREAD

**Issue by dsaul** [geerlingguy/kubernetes-101#38]
Hi Jeff,

In episode 6 I had to use the following ingress yml file instead of the one provided to get it to work, looks like the format has changed.

Regards,
Dan Saul

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drupal
  namespace: drupal
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drupal
            port:
              number: 80
```
