### ISSUE TITLE
episode-03 Image name incorrect

### ISSUE THREAD

**Issue by dstuartkelly** [geerlingguy/kubernetes-101#42]
In episode-03 when we create the deployment and it fails to pull because the secret is not present. After adding the secret it still fails to pull with the same error.
```
Failed to pull image "geerlingguy/kube101-go:1.0.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for geerlingguy/kube101-go, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

This is because the repository `geerlingguy/kube101-go` no longer exists.
I assume the correct repository is `geerlingguy/kube101` with image tag `hello-go` and have worked around the error by editing the deployment to use this image.

```yaml
spec:
  ...
  template:
    ...
    spec:
      containers:
      - image: geerlingguy/kube101:hello-go
```
